### ISSUE TITLE
2.0: UI - Refreshing the page causes a 404

### ISSUE THREAD

**Issue by gopherstein** [supergiant/analyze#34]
![Screen Shot 2018-12-04 at 3:24 PM](http://marker.screenshots.prod.s3.amazonaws.com/7caed7272b0b4c9daaad11427bf11b62-1543937097607.png)

**Summary:**
When refreshing the page in the browser on the Analyze tab, the web page returns a 404.

**Steps to Reproduce:** 
1. Create a cluster and deploy Analyze
2. After opening Analyze, refresh the page.
**Expected Results:** 
The page is refreshed correctly and shows any updated info if there is any.
**Actual Results:** 
A 404 is returned.

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:60201/api/v1/namespaces/kube-system/services/knotted-prawn-analyze:4443/proxy/checks](http://localhost:60201/api/v1/namespaces/kube-system/services/knotted-prawn-analyze:4443/proxy/checks)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1020</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by taaraora** [comment]
fixed on https://github.com/supergiant/analyze/pull/55
